slam_toolbox:
  ros__parameters:
    # ROS Parameters
    save_map_timeout: 10000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65


#ros2 run nav2_map_server map_saver_cli -f ./maps/map --ros-args -p save_map_timeout:=50000 -p free_thresh_default:=0.25 -p occupied_thresh_default:=0.65

