amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2 #2.5    #odom rotation estimate from rotation
    alpha2: 0.2         #odom rotation estimate from translation
    alpha3: 0.2         #odom translation estimate from translation
    alpha4: 0.2         #odom translation estimate from rotation
    alpha5: 0.2         #Not Required For Differential Robot
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 120 #60
    max_particles: 4000 #2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1   #0.0
    recovery_alpha_slow: 0.001 #0.0
    resample_interval: 1 #0.05    #1
    robot_model_type: "nav2_amcl::DifferentialMotionModel" #"differential"
    save_pose_rate: 5 #0.5
    sigma_hit: 0.2
    tf_broadcast: false #true
    transform_tolerance: 1.0   #1.0
    update_min_a: 0.08 #0.2
    update_min_d: 0.25 #0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 30.0 #20
    min_x_velocity_threshold: 0.1 #0.5 #0.001
    min_y_velocity_threshold: 0.1 #0.5
    min_theta_velocity_threshold: 0.05 #0.2 #0.001
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    
    #desired_linear_vel: 0.03
    #desired_angular_vel: 0.053
    #max_angular_accel: 0.05

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3 #0.05 #0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance:  0.5 #0.25
      yaw_goal_tolerance: 0.5 #0.25
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      #desired_linear_vel: 0.15
      
      min_vel_x: 0.08  #0.11
      min_vel_y: 0.0
      max_vel_x: 0.095 #0.12 #0.13
      max_vel_y: 0.0
      min_vel_theta: 0.16  #0.155
      max_vel_theta: 0.18  #0.18
      min_speed_xy: 0.09  #0.11
      max_speed_xy: 0.102 #0.12 #0.13
      min_speed_theta: 1.0
          
      desired_linear_vel: 0.085 #0.12
      lookahead_dist: 0.4 #0.8 #0.6
      min_lookahead_dist: 0.3 #0.3
      max_lookahead_dist: 0.5 #0.9
      lookahead_time: 10.0 #1.5
      rotate_to_heading_angular_vel: 0.18 #0.18 #0.68 #1.8
      transform_tolerance: 0.01
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.01 #0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.3 #0.80 #0.5 #0.25
      use_cost_regulated_linear_velocity_scaling: true #true #false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.05 #0.25
      use_rotate_to_heading: true #true
      allow_reversing: true #false
      rotate_to_heading_min_angle: 0.60 #0.6 #0.5 #0.785
      max_angular_accel: 12.2 #3.2
      max_robot_pose_search_dist: 10.0
      use_interpolation: false #true #false

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency:  35.0 #5.0
      publish_frequency: 35.0  #2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width:  8  #3
      height: 8  #3
      
      origin_x: -6.86 #-1.68 [-6.86, -3.47, 0]
      origin_y: -3.47 #-9.72
      
      resolution: 0.03   #0.05
      robot_radius: 0.28 #0.26 #0.25 #0.22
      
      footprint: "[ [0.22, 0.192], [0.22, -0.192], [-0.22, -0.192], [-0.22, 0.192] ]" #####
      
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"] #["obstacle_layer", "voxel_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0 #0.50 #3.0
        inflation_radius: 0.60 # 0.38 #0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 35.0   #1.0
      publish_frequency: 35.0  #1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.28 #0.26 #0.25   #0.22
      resolution: 0.03     #0.05
      
      width:  16  #3
      height: 16  #3
      origin_x: -6.86 #-1.68  [-6.86, -3.47, 0]
      origin_y: -3.47 #-9.72
      
      track_unknown_space: true
      
      footprint: "[ [0.205, 0.192], [0.205, -0.192], [-0.205, -0.192], [-0.205, 0.192] ]"  ##### "[ [0.205, 0.198], [0.205, -0.198], [-0.205, -0.198], [-0.205, 0.198] ]"
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"] #["static_layer", "obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0 #0.50 #3.0
        inflation_radius: 0.60 #0.38 #0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

#map_server:
#  ros__parameters:
#    use_sim_time: False
#    yaml_filename: "/home/linux-dev/Desktop/FINAL WITH NAV/kbot_mk1/map.yaml" #"turtlebot3_world.yaml"

#map_saver:
#  ros__parameters:
#    use_sim_time: True
#    save_map_timeout: 5000
#    free_thresh_default: 0.25
#    occupied_thresh_default: 0.65
#    map_subscribe_transient_local: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 60.0 #120.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner" #"smac_planner/SmacPlanner2D" #"nav2_navfn_planner/NavfnPlanner"
      tolerance: 5.8  #0.00001 #0.0001 #0.02 #0.5
      use_astar: true #false
      allow_unknown: false #false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: global_costmap/costmap_raw #local_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint #local_costmap/published_footprint
    cycle_frequency: 5.0 #10.0
    recovery_plugins: ["spin", "back_up", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
      #wait_duration: 2.0
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 10.0 #0.1
    use_sim_time: false
    simulate_ahead_time: 5.0 #2.0
    max_rotational_vel: 0.21   #1.0
    min_rotational_vel: 0.18   #0.4
    rotational_acc_lim: 12.2 #5.5    #3.2
    
#waypoint_follower:
#  ros__parameters:
#    loop_rate: 30
#    stop_on_failure: false
#    waypoint_task_executor_plugin: "wait_at_waypoint"
#    wait_at_waypoint:
#        plugin: "nav2_waypoint_follower::WaitAtWaypoint"
#        enabled: True
#        waypoint_pause_duration: 8000  #duration in milliseconds
        
robot_state_publisher:
  ros__parameters:
    use_sim_time: False
